In [1]:
import numpy as np
import math

In [2]:
def lm_P(x: np.ndarray) -> float:
    m = len(x)
    return np.dot(np.arange(1, m + 1), np.array(x))

def P(x: np.ndarray) -> float:
    return math.exp(lm_P(x))



In [3]:
def softmax(x: np.ndarray) -> np.ndarray:
    v =  np.exp(x)
    s = np.sum(v)
    return v / s

softmax(np.arange(1, 5))
    

array([0.0320586 , 0.08714432, 0.23688282, 0.64391426])

In [4]:
def grad_ln_P(x: list[float]) -> np.ndarray:
    return np.arange(1, len(x) + 1) / x

grad_ln_P([1, 1, 2])

array([1. , 2. , 1.5])

In [11]:
def gradient_descent_test(m: int, eta: float = 1e-2, iter: int = 10 ** 3, tol: float = 1e-9) -> np.ndarray:
    # we work on vectors $u$, and return exp(u) as the result.
    u = np.zeros(m)
    s = m * (m + 1) // 2
    
    for _ in range(iter):
        v = np.exp(u - np.max(u))
        z = v / np.sum(v)
        
        g_u = np.arange(1, m + 1) - s * z
        
        if np.linalg.norm(eta * g_u) < tol:
            break
        
        u += eta * g_u
        
    v = np.exp(u - np.max(u))
    z = v / np.sum(v)
    
    return m * z
    
    
    # return x

gradient_descent_test(10)



array([0.18182071, 0.36363591, 0.54545422, 0.72727244, 0.90909064,
       1.09090884, 1.27272703, 1.45454521, 1.6363634 , 1.81818159])

In [16]:
t = 1.0
n = 10
l = gradient_descent_test(n)
for i in range(1, n + 1):
    t *= math.pow(l[i - 1], i)
    # t += i * math.log(l[i - 1])
# math.exp(t)
t

4112.085002442024